test
l1qwy/movies-explorer-frontend pull request #1
Opened 2023-10-26 05:57 UTC by l1qwy

2023-10-26 06:00 UTC, l1qwy commented
Исчезла ветка майн. level-2 стала базовой. Я вроде поправил, но изменения все равно в майн упали

2023-10-26 06:52 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- Хорошо добавить фоновый цвет всему документу, чтобы не было белых полос по бокам.
	- В карточках с фильмами нет кнопок по макету: галочка и крестик
	- Нет разметки для неавторизованного пользователя https://yadi.sk/d/aiXYymirYcZfyg
	- https://yadi.sk/d/tytiF-HASc3BZw https://yadi.sk/d/owE3H3b3CfKSgg На больших мониторах отступы не по макету
	- https://yadi.sk/d/PwBx5UTGiFHqPw на больших мониторах карточки две в ряд
	- https://yadi.sk/d/Lg8O5wk3JxHaOw https://yadi.sk/d/D_hz6J_DzOliSQ - перенос не по макету
	- На Странице Сохраненные фильмы нет кнопки Еще и отступ отличается от макета на всех разрешениях.

	**Главная**
	- 1280 https://yadi.sk/d/W8CBar_hGzFZjA https://yadi.sk/d/4C2gLbZ234WSQw
	- 768 https://yadi.sk/d/Iy-aE_RZ-rA1xA https://yadi.sk/d/DjWdjucqp7gYIg
	- 320 https://yadi.sk/d/G8jxa6Ti0YQJSQ

	**Авторизация**
	- https://yadi.sk/d/oaL6l8xSa9LOkA
	- 320 https://yadi.sk/d/wMwd6LWEOQg8yA

	**Фильмы**
	- 1280 https://yadi.sk/d/svULZdwCz6DNfw https://yadi.sk/d/PjzUy01kbx-o3g https://yadi.sk/d/7mpxC_qD31tx3g
	- 768 https://yadi.sk/d/bajwdk_oyQhD3g
	- 320 https://yadi.sk/d/6i5T57Eal6FRCA

	**Меню**
	- 768 https://yadi.sk/d/Xb3PcUVcrmgakw
	- 320 https://yadi.sk/d/KsacI68lOCxy3w

	**Профиль**
	- 768 https://yadi.sk/d/81l7e1P-7u-4AQ
	- 320 https://yadi.sk/d/tMLopXnExKXn2w

	**404**
	- 320 https://yadi.sk/d/vh7qH-2F00HxhQ

	**Можно лучше**
	Для контроля отображения, очень рекомендую воспользоваться плагином PerfectPixel для Chrome, экспортируйте весь макет картинкой и откройте проект в браузере, добавьте картинку в плагин открытый в браузере, выставите масштабирование 1, вы сможете сами контролировать отображение вашей страницы, например: https://monosnap.com/file/jwX9oWyFyWZKy9Akf60w4OAC7i2UX9

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- Главная https://yadi.sk/d/W2OHRowGdo2Yaw https://yadi.sk/d/vtduOd9vXylRPw https://yadi.sk/d/Z7R-cZCXXKYxbQ https://yadi.sk/d/w80KtZ4EY31MgQ
	- Авторизация https://yadi.sk/d/ZR2tiQ7lnY096A
	- Фильмы https://yadi.sk/d/i40R0XLF63w7GA - Обратите внимание, что при сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

	- aboutMe__git, - хорошо оформить ссылкой с указанием на ресурс, подзодящим классом и ховер эффектом.
	- footer__copyring-sites - аналогичное замечание - список со ссылками в подвале
	- Выйти из аккаунта - хорошо бы добавить переход на Авторизацию

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/AjSXjCZI1KZe6w https://yadi.sk/d/irX0AKGSKFM3Dw - В проекте есть ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)
	- aboutMe, aboutProject, header__homePage и т.д. - Используйте единообразное именование классов в кебаб-кейсе, скорректируйте все подобные случаи самостоятельно
	- aboutProject__schematic-backend и aboutProject__schematic-frontend, navigation__img и navigation__img-close, profile__logout и profile__submit - Используйте одинаковый класс для одинаковых смысловых элементов. Если требуется отделить визуально второй, можно добавить модификацию, т.е. к первому классу добавить еще один корректирующий.
	- header__logo_auth - хорошо подойдет сложный модификатор вместо булевого - header__logo_type_auth, скорректируйте все подобные случаи самостоятельно
	- form__field_register, form__submit_login, form__note_link и т.д. - аналогичное замечание со сложным модификатором.

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- см. пункт с адаптивом

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/o0_JvlyTdeKxGA https://yadi.sk/d/i3MzjmDW7dRQOw https://yadi.sk/d/j6xFLMZLPpkeRg - Проект содержит ошибки валидации, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- В проекте есть ошибки в консоли
	- Каждой отдельной странице нужен заголовок 1 уровня (Вход/Рег/Профиль/404)
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Вход/Рег/Профиль/404)
	- Карточке с фильмами следует добавить семантический заголовок - можно 2 уровня
	- navigation__img и navigation__img-close - Это кнопка - элемент `button`, но не картинка. Все кнопки должны быть объявлены с помощью тега `<button>` и иметь атрибут `type`. Так же все интерактивные элементы должны реагировать на наведение мышью.
	- navigation__container - Обертка для данных элементов - тег `nav`. Этим элементом принято выделять список из ссылок, отвечающий за навигацию по сайту и не только. Добавление этого элемента улучшает восприятие вашей верстке машинами, в т.ч скринридерами. Можно использовать несколько тегов `nav` в проекте. https://doka.guide/html/nav/
	- navigation__profile-logoImg, navigation__img, navigation__img-close, portfolio__link-img, promo__img - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- br - не используйте жесткие переносы в разметке
	- nobr - хорошо вместо него использовать неразрывный пробел https://doka.guide/html/deprecated-tags/
	- techs__schema - в блоке текст обернут дивами, что ухудшает семантику, здесь можно лучше использовать семантический список ul-li

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- form__field-label, profile__field-label - расположите якоря в поточном режиме, чтобы не вырывать из потока.

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинк [...]

2023-10-27 12:12 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово второе ревью на Ваш проект. Неплохая работа, несколько пунктов засчитано.
Баллов пока недостаточно, для того, чтобы его принять, зато есть возможность улучшить работу и получить максимальный балл. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- Контент тянется на весь экран на больших мониторах, хорошо бы добавить ему фиксацию по макету (1280пх) и центрировать относительно вьюпорта. В этом могут помочь сво-ва max-width, margin.
	- https://yadi.sk/d/sGpo6lJ1yOu3gw На Странице Сохраненные фильмы нет кнопки Еще и отступ отличается от макета на всех разрешениях.

	**Главная**
	- 1280 https://yadi.sk/d/qecIHjJKjVFyQQ
	- 320 https://yadi.sk/d/NbtF8T16cXTvhg https://yadi.sk/d/UlGZr4fUEtyC2Q

	**Авторизация**
	- 320 https://yadi.sk/d/OYn0VHVVEZlXpQ

	**Фильмы**
	- 1280 https://yadi.sk/d/liL4-X9wh7wq3Q
	- 768 https://yadi.sk/d/xdupGR9B1Zd1bg

	**Меню**
	- 768/320 https://yadi.sk/d/XB_utBskeSoKmA

	**Профиль**
	- 320 https://yadi.sk/d/35lRdnJcVfZCPg

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- Главная https://yadi.sk/d/SUHA-Yy87yVQzQ https://yadi.sk/d/ggbSdjaN1JnlTw
	- Авторизация https://yadi.sk/d/SY_GDC0OawtIRw
	- Фильмы https://yadi.sk/d/E5r3EHON6zfCvg https://yadi.sk/d/e_lf8M5igcrsCg - Сохраняется гор.прокрутка при сужении. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- Сохраняются ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)
	- header-auth__loginBtn, header__homePage, promo__textContainer, savedMovies, searchForm и т.д. - еще не все скорректировано под кебаб-кейс, скорректируйте все подобные случаи самостоятельно
	- about-project__schematic (мобидикаторы без сущности), profile__submit_edit и profile__submit_logout - У всех одинаковыйх элементов следует ставить один класс, например кнопки в профиле одинаковые - оформите их селектором button устанавливаете класс `profile__button`, у той кнопки где нужно что-то скорректировать добавляется модификатор `profile__button profile__button_theme_outline` и так во всех аналогичных случаев.

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- см. пункт с адаптивом

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- Проект содержит ошибки валидации, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- https://yadi.sk/d/41rtpkXi3PzVGQ, navigation__profile-logoImg, portfolio__link-img, promo__img - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- https://yadi.sk/i/cOa3u3ZYIj8dSg - контента внутри параграфа нет, можно его или удалить или переместить внутрь контент
	- https://yadi.sk/d/cERR1pGFAyKrVA кнопка внутри ссылки в текущей разметке неоправдана, ссылку можно стилизовать как кнопку с помощью доп.класа/модификатора.

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- form__field-label, profile__field-label - расположите элементы в поточном режиме, чтобы не вырывать из потока на absolute.

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.

	- В хедере неавторизованный пользователь - это не отдельный компонент, а вариант навигации, т.к. идет дублирование https://yadi.sk/i/0Ba5HDVsWBpuoA

- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Необходимо добавить также валидацию на пустые поля формы, при попытке авторизоваться

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

	- promo-logo.svg - скачайте изображение в формате png

## Количество баллов: 53

## Доп. Комментарии:
	- Лишние(не используемые) шрифты следует удалить из проекта / Лишние подключения @font-face так же следует удалить

2023-10-28 08:51 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово третье ревью на Ваш проект. 
Здесь немного пунктов засчитано было, еще следует скорректировать адаптивную верстку, чтобы не было прокрутки (там хороший бал), соответствие по макету (не так много работы, тоже хороший бал), семантическая разметка.
Обращаю Ваше внимание, что итерация у Вас остается последней. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- Фоновый цвет задайте для всего документа, селектору app, для того, чтобы не было белых полос по бокам, тема темная, светлый цвет не по макету. Создайте контейнер внутри app (.app__content) для того, чтобы в нем описать мак.ширину и выравнивание по центру.
	- https://yadi.sk/d/DqjVTwaTc1z0kg - на больших экранах карточки по две (что не по макету)
	- https://yadi.sk/d/nulZgaXDyA-P0A - сохраненные фильмы (в карточках панель для удаления фильма), отступ до подвала не по макету
	- https://yadi.sk/d/aWE7emx4JELj1w на больших мониторах отступы отличаются

	**Главная**
	- 320 https://yadi.sk/d/XwzZfSa2VBErIA

	**Авторизация**
	- 320 https://yadi.sk/d/G9YiszXuQzKGAg

	**Меню**
	- 768/320 https://yadi.sk/d/XB_utBskeSoKmA

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- Главная https://yadi.sk/d/haUvY_7mEJLUbA https://yadi.sk/d/iXMAquXVL0l4jA https://yadi.sk/d/3FHP7s60DIOHuw
	- Авторизация https://yadi.sk/d/nfQ258HisVwGvQ
	- Профиль https://yadi.sk/d/XcVv7cX24iw9sw - Сохраняется гор.прокрутка при сужении. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/ewFkZyRky_ddTw Сохраняются ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- см. пункт с адаптивом

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/1afLjlFowQyXcA Проект содержит ошибки валидации, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- https://yadi.sk/d/41rtpkXi3PzVGQ, navigation__profile-logoImg, portfolio__link-img, promo__img - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- profile__field-label - расположите элементы в поточном режиме, чтобы не вырывать из потока на absolute.

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Необходимо добавить также валидацию на пустые поля формы, при попытке авторизоваться

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 57

2023-10-30 08:38 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
У Вас получилась достойная работа. Поздравляю Ваш проект принят, желаю Вам дальнейших успехов во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	**Меню**
	- 768/320 https://yadi.sk/i/crQ2uimLdGzYtQ установите минимальный размер по высоте экрана, и при помощи флекса расположите Аккаунт внизу задав внутренние отступы родительскому контейнеру.

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/yyUsSbnRFSTRPQ оформите ссылку на профиль одним селектором `a href` для того, чтобы не было дублирований и между ними не было отступа, т.к. это один интерактивный элемент по логике.
	- https://yadi.sk/d/41rtpkXi3PzVGQ, navigation__profile-logoImg, portfolio__link-img, promo__img - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 85

	- Необходимо добавить также валидацию на пустые поля формы, при попытке авторизоваться
	- Фоновый цвет задайте для всего документа, селектору app, для того, чтобы не было белых полос по бокам, тема темная, светлый цвет не по макету. Создайте контейнер внутри app (.app__content) для того, чтобы в нем описать мак.ширину и выравнивание по центру.

2023-10-30 18:34 UTC, merged